# -*- coding: utf-8 -*-
#
# Configuration file for the Sphinx documentation builder.
#
# This file does only contain a selection of the most common options. For a
# full list see the documentation:
# http://www.sphinx-doc.org/en/master/config

# -- Path setup --------------------------------------------------------------

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#
# import os
# import sys
# sys.path.insert(0, os.path.abspath('.'))


# -- Project information -----------------------------------------------------

project = 'QMint Playground'
copyright = '2026 PinT Community'
author = 'PinT Community'

# The short X.Y version
version = ''
# The full version, including alpha/beta/rc tags
release = ''


# -- General configuration ---------------------------------------------------

# If your documentation needs a minimal Sphinx version, state it here.
#
# needs_sphinx = '1.0'

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
    'autoapi.extension',
    'sphinx.ext.mathjax',
    'sphinx.ext.viewcode',
    'sphinx.ext.napoleon',
    'sphinx.ext.extlinks',
    'sphinx_design',
    'sphinx_copybutton',
    'sphinx_favicon',
    'myst_parser',
    'nbsphinx',
]

myst_enable_extensions = [
    "amsmath",
    "dollarmath",
    "colon_fence",
    "substitution",
]
myst_heading_anchors = 2

favicons = [
    "android-chrome-192x192.png",
    "android-chrome-512x512.png",
    "apple-touch-icon.png",
    "favicon-16x16.png",
    "favicon-32x32.png",
    "favicon.ico",
]

add_module_names = False
autoapi_type = 'python'
autoapi_dirs = ['../qmint']
autoapi_file_patterns = ['*.py']
autoapi_options = [
    'members', 'undoc-members',
    'show-inheritance-diagram',
    'show-module-summary',
    ]
autoapi_python_class_content = 'both'
autoapi_add_toctree_entry = False
autoapi_ignore = [
    '*scripts*'
    '*playgrounds*'
    ]
autoapi_root = "api"

autoapi_keep_files = False

napoleon_use_param = False
napoleon_use_keyword = False
napoleon_use_ivar = True

extlinks = {'repo': ('https://github.com/Parallel-in-Time/qmint/tree/main/%s', None)}

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# The suffix(es) of source filenames.
source_suffix = ['.rst', '.md']

# The master toctree document.
master_doc = 'index'

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = 'en'

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This pattern also affects html_static_path and html_extra_path .
exclude_patterns = ['_build', 'Thumbs.db', '.DS_Store']

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = "solarized-light"
pygments_dark_style = "solarized-dark"

copybutton_exclude = ".linenos, .gp"
copybutton_selector = ":not(.prompt) > div.highlight pre"

# -- Options for HTML output -------------------------------------------------
html_theme = 'pydata_sphinx_theme'

html_logo = "_static/sdc_logo.png"
html_theme_options = {
    "logo": {
        "text": "QMint Playground",
        "image_light": "_static/sdc_logo.png",
        "image_dark": "_static/sdc_logo.png",
    },
    "use_edit_page_button": True,
    'globaltoc_maxdepth': 2,
}

html_context = {
    "github_user": "Parallel-in-Time",
    "github_repo": "qmint",
    "github_version": "main",
    "doc_path": "docs",
}

html_static_path = ['_static']
html_css_files = ['custom.css']